# Generated by Django 2.0 on 2018-02-06 09:45

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('age_max', models.IntegerField(blank=True, default=64)),
                ('age_min', models.IntegerField(blank=True, default=25)),
                ('employment_status', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Full time'), (2, 'Part time'), (3, 'Self employed'), (4, 'Unemployed'), (5, 'Home maker'), (6, 'Retired')], default=1)),
                ('income_min', models.FloatField(blank=True, default=1000)),
                ('loan_amount_min', models.FloatField(blank=True, default=500)),
                ('loan_amount_max', models.FloatField(blank=True, default=2000)),
                ('employer', models.BooleanField(default=True)),
                ('occupation', models.BooleanField(default=True)),
                ('postcode', models.BooleanField(default=True)),
            ],
        ),
    ]
