# Generated by Django 2.0 on 2018-02-06 10:10

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tm', '0002_callcredit_setting'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallCredit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('credit_score', models.IntegerField(null=True)),
                ('credit_score_with_mortgage', models.IntegerField(null=True)),
                ('indebt_min', models.FloatField(null=True)),
                ('delinquent_mortgage', models.BooleanField(default=False)),
                ('active_bunkruptcy', models.BooleanField(default=False)),
                ('debt_in_income_min', models.FloatField(null=True)),
                ('debt_in_income_max', models.FloatField(null=True)),
                ('last_credit', models.DateTimeField(null=True)),
                ('confidence_factor', models.FloatField(null=True)),
                ('indicator_red', models.BooleanField(default=False)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='callcredits', to='tm.Applicant')),
            ],
        ),
    ]
