# Generated by Django 2.0 on 2018-02-09 07:25

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tm', '0003_callcredit'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.PositiveSmallIntegerField(choices=[(1, 'Success'), (2, 'Wrong data'), (5, 'Rejected internal'), (6, 'Rejected call credit')])),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='tm.Applicant')),
                ('call_credit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='tm.CallCredit')),
            ],
        ),
    ]
