# Generated by Django 2.0 on 2018-02-24 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tm', '0004_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='addr_credit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='addr_electral_roll',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='no_dd',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
