# Generated by Django 2.0 on 2018-02-27 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tm', '0005_auto_20180224_0334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='employer',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='setting',
            name='occupation',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='setting',
            name='postcode',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
