# Generated by Django 2.0 on 2018-03-14 04:18

from django.db import migrations, models
import tm.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('tm', '0007_auto_20180302_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='sms_token',
            field=models.CharField(default=tm.helpers.gen_token, max_length=32),
        ),
    ]
