# Generated by Django 2.0 on 2018-03-18 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tm', '0010_auto_20180316_0414'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanOutstand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lender', models.CharField(max_length=50)),
                ('amount', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='tm.Applicant')),
            ],
        ),
    ]
