# Generated by Django 2.0 on 2018-03-18 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tm', '0011_loanoutstand'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='is_phone_verified',
            field=models.BooleanField(default=False),
        ),
    ]
