# Generated by Django 2.0 on 2018-03-19 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tm', '0012_applicant_is_phone_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='reference_number',
            field=models.IntegerField(null=True),
        ),
    ]
