# Generated by Django 2.0 on 2018-04-09 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tm', '0015_auto_20180407_0543'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='credit_score_min_no_mortgage',
            field=models.IntegerField(blank=True, default=490),
        ),
        migrations.AddField(
            model_name='setting',
            name='dti_ratio_max',
            field=models.IntegerField(blank=True, default=24),
        ),
        migrations.AddField(
            model_name='setting',
            name='dti_ratio_min',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='introducer',
            name='auth_code',
            field=models.CharField(default='0jRP0PMNbvCNYn9oMd2jj46RSHdv2tuwDcPVW9XWesQcMWPKByxBDam1NVy1fcq7', max_length=64),
        ),
        migrations.AlterField(
            model_name='setting',
            name='credit_score_min',
            field=models.IntegerField(blank=True, default=470),
        ),
    ]
